### ISSUE TITLE
terminate called after throwing an instance of 'tf2::LookupException'

### ISSUE THREAD

**Issue by aadityasaraiya** [AustinDeric/yak#18]
Hi! 

I am Aaditya Saraiya and I am currently working on the [Google Summer of Code 2018](https://github.com/ros-industrial/workcell_explorer) project with ROS Industrial under the mentorship of @Levi-Armstrong.

I want to use the yak package with my project for 3-D reconstruction with a Kinect mounted on a robotic manipulator. I tried the ``roslaunch yak launch_xtion_robot.launch`` command after launching the RViz planning/execution file, when I get this error.
~~~
terminate called after throwing an instance of 'tf2::LookupException'
what():  "ensenso_sensor_optical_frame" passed to lookupTransform argument source_frame does not exist.
~~~

I am currently using a simulated Kinect from Gazebo. I tried changing the topic names to match with the topic names from my package but that didn't seem to solve the issue. Can you please guide me on how to remove this error as well as how I should start off using this package? Some hints on what parameters I should change just to start off would be very helpful. 

Edit: Have just added the tf tree for reference
[frames1.pdf](https://github.com/AustinDeric/yak/files/2133507/frames1.pdf)

Thanks in advance,
Aaditya Saraiya

**Comment by aadityasaraiya** [comment]
**Update:**

So after viewing the tf tree I realised that the `ensenso_sensor_optical_frame` did not exist. After making that change in the `kinfu_server.cpp` file, I am receiving the following error 

~~~
terminate called after throwing an instance of 'tf2::LookupException'
  what():  "volume_pose" passed to lookupTransform argument target_frame does not exist.
~~~

while in fact when viewing the tf tree, the `volume_pose` frame does exist. So that's a bit weird.

**Comment by schornakj** [comment]
An overarching issue is that lots of important parameters are hardcoded, so some of the nodes are expecting to see a specific robot and sensor configuration that's not completely represented in the launch file. It also looks for some robot configuration data that's set up by the MoveIt Setup Assistant. The package was developed on the robot from the [Godel blending demo](https://github.com/ros-industrial-consortium/godel), so most of the parameters point at frames and other things from there. In this case from your first comment, `ensenso_sensor_optical_frame` should be changed to the frame at the origin of the depth image.

Are you also running the other launch file for octomap reconstruction and running the `nbv_planner` node? `volume_pose` is the center of the TSDF volume, and it's supposed to be moveable by dragging some handles in Rviz. I think that the transform from the `base_link` frame is set and updated in `volume_tf_broadcaster.cpp`, so if you can't see `volume_pose` I'd start by checking there.

**Comment by aadityasaraiya** [comment]
@schornakj Thanks for the response. I will make the change regarding changing `ensenso_sensor_optical_frame` to the depth frame. 

I wasn't running the `nbv_planner node`, so I will try running the same and report back what I get. I realized that about `volume_tf_broadcaster.cpp` and I will have a look at it to search for a potential issue. 

Regarding the interactive volume thing in RViz, I am currently simulating objects in Gazebo. @Levi-Armstrong suggested that I could use gl_depth_sim instead, however, I have stuck to Gazebo as of now. 

Thanks again. 

**Edit:** Running the `nbv_planner` node doesn't make a difference.

**Comment by aadityasaraiya** [comment]
@schornakj So I analyzed it further. First of all, there were warning regarding my tf tree not being proper, which was solved after changing parameters in the `world_to_base_publisher` node parameters in Line 4 of the `launch_xtion_robot.launch` [file](https://github.com/AustinDeric/yak/blob/master/yak/launch/launch_xtion_robot.launch).  

On certain trials, the node suddenly starts working with successful tracking and planning. While sometimes it shows the following error:

~~~
terminate called after throwing an instance of 'tf2::LookupException'
 what():  "volume_pose" passed to lookupTransform argument target_frame does not exist.
~~~
 On some 3-4 occasions it showed the following error (time values used to be different in the error):

~~~
Unable to transform object from frame 'map' to planning frame '/world' (Lookup would require extrapolation at time 367.223000000, but only time 367.323000000 is in the buffer, when looking up transform from frame [map] to frame [world]).
~~~

So, according to [this](https://answers.ros.org/question/188046/tf-lookup-would-require-extrapolation-into-the-future/), it's definitely some time-related issue because of which the transform isn't available when ` tf::lookupTransform ` is being performed in Line 26 in the [kinfu_server.cpp program](https://github.com/AustinDeric/yak/blob/master/yak/src/ros/kinfu_server.cpp). I have tried increasing the time in the `tf::waitForTransform` but it doesn't help. Any thoughts on why this could be happening? I have attached the new tf tree as well. 

[frames2.pdf](https://github.com/AustinDeric/yak/files/2137206/frames2.pdf)

Thanks!

**Comment by aadityasaraiya** [comment]
Hi!

So the issue was occuring because the node used to terminate with the error message when the `volume_pose` frame was not available. However, with the [given pull request](https://github.com/AustinDeric/yak/pull/19), I have added exception handling which allows the node to continue as soon as the frame becomes available.
